### ISSUE TITLE
Failed to download

### ISSUE THREAD

**Issue by Rheliken** [m4eba/eurosportplayer-downloader#1]
key 1ee945b0ca0aa8b58400c65a173dd749
base https://eurosport-dlvr-ott.akamaized.net/primary/2/59aa63875a7749b0828b0b576744e3d9/start/1581255600/end/1581260640/index.mpd
period duartion PT5042.000S
TypeError: Cannot read property '0' of undefined
    at processAdaptionSet (C:\Users\Heliken\Downloads\eurosportplayer-downloader-master\eurosportplayer-downloader-master\dash.js:39:35)
    at download (C:\Users\Heliken\Downloads\eurosportplayer-downloader-master\eurosportplayer-downloader-master\dash.js:169:19)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async C:\Users\Heliken\Downloads\eurosportplayer-downloader-master\eurosportplayer-downloader-master\download.js:285:7
Error: unable to process mpd TypeError: Cannot read property '0' of undefined
    at download (C:\Users\Heliken\Downloads\eurosportplayer-downloader-master\eurosportplayer-downloader-master\dash.js:199:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async C:\Users\Heliken\Downloads\eurosportplayer-downloader-master\eurosportplayer-downloader-master\download.js:285:7

Can you help me solve it?

**Comment by m4eba** [comment]
what is the url to the video you want to download?

**Comment by Rheliken** [comment]
https://www.eurosportplayer.com/videos/eurosport/volta-a-la-comunitat-valenciana-ambient-sound-606854

**Comment by m4eba** [comment]
there were a few problems:
-the SegmentTemplate was one level up inside the AdaptationSet
-the urls to the segments were build incorrectly
-the video uses 2 different keys for decryption

i fixed the first two and i'm working on the decryption problem
but i noticed the video now is using the 'working format', so the current version should work again!

**Comment by m4eba** [comment]
for the record: 
was unable to decrypt the files with neither mp4decrypt nor shaka-packager
the problem was a different KID in the tenc atom and the pssh ones, worked with a modified tenc atom having the pssh KID.

but doesn't matter anymore, see #2
